version: "3.9"

services:
  navigator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: navigator
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      TZ: ${TZ}
    networks:
      - soc_shared

networks:
  soc_shared:
    external: true