version: "3.9"

services:
  cyberchef:
    image: ghcr.io/gchq/cyberchef:10.22
    container_name: cyberchef
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      TZ: ${TZ}
    networks:
      - soc_shared

networks:
  soc_shared:
    external: true